#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /script_dir/clone ensure=absent force=true
puppet resource file /script_dir ensure=directory
puppet resource file /script_dir/clone ensure=directory
cd /script_dir/clone
git clone https://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@github.com/bcsim-git/devops_repo.git
cp -p /testdir/clone/operate_18061692/index.html /var/www/html
